spring:
  application:
    name: pet-adoption-api

  datasource:
    url: jdbc:postgresql://localhost:5432/adocao_db
    username: postgres
    password: sua_senha

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true