spring:
  application:
    name: pet-adoption-api

    datasource:
      url: jdbc:mysql://localhost:3306/adocao_db
      username: root
      password: sua_senha

      jpa:
        hibernate:
          ddl-auto: update

        show-sql: true

        properties:
          hibernate:
            format_sql: true
